# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=com.lsz.carpet-willowbranch-addition

# Dependencies
fabric_api_version=0.155.2+26.2
carpet_version=8261203